package grupo7_poryectofinalsm;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import login.*;
import proyecto.*;
        
public class TableroStratego extends JFrame {
    Persona persona;
    VentaLogin ventana;
    private JButton[][] botones = new JButton[10][10];
     private BufferedImage image;
     private Personaje[] heroes = new Personaje[33];
     private Personaje[] villanos = new Personaje[33];
     private Personaje[] bombasH = new Personaje[6];
     private Personaje[] bombasV = new Personaje[6];
     private Personaje TierraH;
     private Personaje TierraV;
     
    public TableroStratego(VentaLogin ventana, Persona persona) {
        this.setExtendedState(6);
        initComponents();
        initBotones();
          this.persona=persona;
        this.ventana=ventana;
        initPersonajes();
        setPersonajes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_menu.setText("MENU");
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn_menu)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addComponent(btn_menu)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseClicked
       menu_principal menu = new menu_principal(ventana,persona);
    menu.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btn_menuMouseClicked

     private void initBotones(){
       GridLayout botonesLayout = new GridLayout(10,10);
       jPanel1.setLayout(botonesLayout);
       for(int f=0; f<10;f++) {
            for(int c=0;c<10;c++){
                botones[f][c] = new JButton();
                botones[f][c].setName("boton_"+String.valueOf(f*c));
                botones[f][c].setBorder(javax.swing.BorderFactory.createEtchedBorder());
                botones[f][c].setOpaque(false);
                botones[f][c].setContentAreaFilled(false);
                botones[f][c].addMouseListener(new MouseAdapter() {
                        public void mouseClicked(MouseEvent evt) {
                                botonesMouseClicked(evt);
                        }
                });
                botones[f][c].addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent evt) {
                        botonesActionPerformed(evt);
                    }
                });
                botones[f][c].addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                    public void propertyChange(java.beans.PropertyChangeEvent evt) {
                        botonesPropertyChange(evt);
                    }
                });
                jPanel1.add(botones[f][c]);
            }
        }
       botones[4][6].setText("Area Prohibida");
       botones[4][6].setEnabled(false);
       botones[5][6].setText("Area Prohibida");
       botones[5][6].setEnabled(false);
       botones[4][7].setText("Area Prohibida");
       botones[4][7].setEnabled(false);
       botones[5][7].setText("Area Prohibida");
       botones[5][7].setEnabled(false);
       
       botones[4][2].setText("Area Prohibida");
       botones[4][2].setEnabled(false);
       botones[5][2].setText("Area Prohibida");
       botones[5][2].setEnabled(false);
       botones[4][3].setText("Area Prohibida");
       botones[4][3].setEnabled(false);
       botones[5][3].setText("Area Prohibida");
       botones[5][3].setEnabled(false);
    }
     
    private void botonesMouseClicked(MouseEvent evt) {
        // TODO add your handling code here:
    }   
    private void botonesActionPerformed(java.awt.event.ActionEvent evt) {
//        Object source = evt.getSource();
//        String Name = ((JButton) source).getName();
//        int bWidth =((JButton) source).getWidth();
//        int bHeight = ((JButton) source).getHeight();
//        int offset = ((JButton) source).getInsets().left;
//        if(Name.equals("0")) {
//            ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes_rebeca/10.mr_fantastic.png"));            
//            Icon iconr = resizeIcon(icon , bWidth - offset , bHeight - offset);
//            botones[0][0].setIcon(iconr); 
//        }
    }
    private void botonesPropertyChange(java.beans.PropertyChangeEvent evt) {
// TODO add your handling code here:
    }
    
    private static Icon resizeIcon(ImageIcon icon, int resizedWidth, int resizedHeight) {
        Image img = icon.getImage();  
        Image resizedImage = img.getScaledInstance(resizedWidth, resizedHeight,  java.awt.Image.SCALE_SMOOTH);  
        return new ImageIcon(resizedImage);
    }
    
    private void initPersonajes() {
        heroes[0] = new Personaje("Heroe", 10, "Mr Fantastic", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[1] = new Personaje("Heroe", 9, "Captain America", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[2] = new Personaje("Heroe", 8, "Professor X", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[3] = new Personaje("Heroe", 8, "Nick Furry", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[4] = new Personaje("Heroe", 7, "Spider Man", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[5] = new Personaje("Heroe", 7 ,"Wolverine", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[6] = new Personaje("Heroe", 7, "Namor", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[7] = new Personaje("Heroe", 6, "Daredevil", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[8] = new Personaje("Heroe", 6, "Silver Surfer", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[9] = new Personaje("Heroe", 6, "Hulk", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[10] = new Personaje("Heroe", 6, "Iron Man", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[11] = new Personaje("Heroe", 5, "Thor", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[12] = new Personaje("Heroe", 5, "Human Torch", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[13] = new Personaje("Heroe", 5, "Cyclops", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[14] = new Personaje("Heroe",5, "Invisible Woman", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[15] = new Personaje("Heroe", 4, "Ghost Rider", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[16] = new Personaje("Heroe", 4, "Punisher", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[17] = new Personaje("Heroe", 4, "Blade", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[18] = new Personaje("Heroe", 4, "Thing", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[19] = new Personaje("Heroe", 3, "Emma Frost", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[20] = new Personaje("Heroe", 3, "She Hulkr", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[21] = new Personaje("Heroe", 3, "Giant Man", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[22] = new Personaje("Heroe", 3, "Beast", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[23] = new Personaje("Heroe", 3, "Colossus", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[24] = new Personaje("Heroe", 1, "Black Widow", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[25] = new Personaje("Heroe", 2, "Phoenix", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[26] = new Personaje("Heroe", 2, "Elektra", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[27] = new Personaje("Heroe", 2, "Dr Strange", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[28] = new Personaje("Heroe", 2, "Nightcrawler", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[29] = new Personaje("Heroe", 2, "Gambit", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[30] = new Personaje("Heroe", 2, "Spider Girl", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[31] = new Personaje("Heroe", 2, "Ice Man", "/Imagenes_rebeca/10.mr_fantastic.png");
        heroes[32] = new Personaje("Heroe", 2, "Storm", "/Imagenes_rebeca/10.mr_fantastic.png");

        
        villanos[0] = new Personaje("Villano", 10, "Dr Doom", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[1] = new Personaje("Villano", 9, "Galactus", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[2] = new Personaje("Villano", 8, "Kingpin", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[3] = new Personaje("Villano", 8, "Magneto", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[4] = new Personaje("Villano", 7, "Apocalypse", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[5] = new Personaje("Villano", 7 ,"GreenGoblin", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[6] = new Personaje("Villano", 7, "Venom", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[7] = new Personaje("Villano", 6, "Bullseye", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[8] = new Personaje("Villano", 6, "Omega Red", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[9] = new Personaje("Villano", 6, "Onslaught", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[10] = new Personaje("Villano", 6, "Red Skull", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[11] = new Personaje("Villano", 5, "Mystique", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[12] = new Personaje("Villano", 5, "Mysterio", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[13] = new Personaje("Villano", 5, "Dr Octopus", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[14] = new Personaje("Villano",5, "Deadpool", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[15] = new Personaje("Villano", 4, "Abomination", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[16] = new Personaje("Villano", 4, "Thanos", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[17] = new Personaje("Villano", 4, "Black Cat", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[18] = new Personaje("Villano", 4, "Sabretooth", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[19] = new Personaje("Villano", 3, "Juggernaut", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[20] = new Personaje("Villano", 3, "Rhino", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[21] = new Personaje("Villano", 3, "Carnage", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[22] = new Personaje("Villano", 3, "Mole Man", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[23] = new Personaje("Villano", 3, "Lizzard", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[24] = new Personaje("Villano", 1, "Black Widow", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[25] = new Personaje("Villano", 2, "Mr Sinister", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[26] = new Personaje("Villano", 2, "Sentinel 1", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[27] = new Personaje("Villano", 2, "Ultron", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[28] = new Personaje("Villano", 2, "Sand Man", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[29] = new Personaje("Villano", 2, "Leader", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[30] = new Personaje("Villano", 2, "Viper", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[31] = new Personaje("Villano", 2, "Sentinel 2", "/Imagenes_rebeca/10.mr_fantastic.png");
        villanos[32] = new Personaje("Villano", 2, "Elektro", "/Imagenes_rebeca/10.mr_fantastic.png");
    }
    
    private void setPersonajes(){
        int colTH = getRandom(1,8);
        botones[9][colTH].setText("Tierra H");
        botones[9][colTH-1].setText("NovaBlast");
        botones[9][colTH+1].setText("NovaBlast");
        botones[8][colTH].setText("NovaBlast");
        int nb=1; //Nueva Bomba
        while(nb<=3){
            int f=getRandom(8,9);
            int c=getRandom(0,9);
            if(botones[f][c].getText().equals("")) {
                botones[f][c].setText("NovaBlast");
                nb++;
            }
        }
        // ubicando heroes
        for(int posicion_heroe=32;posicion_heroe>=0;posicion_heroe--) {
            int heroe_actual = posicion_heroe;
            while(posicion_heroe==heroe_actual) {
                int f,c;
                if(heroes[posicion_heroe].Nivel==2)
                    f = getRandom(6,7);
                else
                    f = getRandom(6,9);
                c =getRandom(0,9);
                if(botones[f][c].getText().equals("")) {
                    botones[f][c].setText(heroes[posicion_heroe].Nombre);
                    heroe_actual--;
                }
            }
        }
        
        int colTV = getRandom(1,8);
        botones[0][colTV].setText("Tierra V");
        botones[0][colTV-1].setText("PumpkinBomb");
        botones[0][colTV+1].setText("PumpkinBomb");
        botones[1][colTV].setText("PumpkinBomb");
        int pb=1;
        while(pb<=3){
            int f=getRandom(0,1);
            int c=getRandom(0,9);
            if(botones[f][c].getText().equals("")) {
                botones[f][c].setText("PumpkinBomb");
                pb++;
            }
        }
        
        // ubicando villanos
        for(int posicion_villano=32;posicion_villano>=0;posicion_villano--) {
            int villano_actual = posicion_villano;
            while(posicion_villano==villano_actual) {
                int f,c;
                if(villanos[posicion_villano].Nivel==2)
                    f = getRandom(2,3);
                else
                    f = getRandom(0,3);
                c =getRandom(0,9);
                if(botones[f][c].getText().equals("")) {
                    botones[f][c].setText(villanos[posicion_villano].Nombre);
                    villano_actual--;
                }
            }
        }
        
    }
    
    private int getRandom(int min, int max) {
        return (int)Math.floor(Math.random() * (max - min + 1) + min);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
